using System;

namespace DemonViglu.FirePlay.Activity
{
    /// <summary>
    /// Stable target namespace shared by realtime delivery and future async
    /// persistence. The ID itself is always supplied by the authority/domain
    /// adapter; this type never stores a Unity object reference.
    /// </summary>
    public enum ActivityTargetKind
    {
        None = 0,
        Player = 1,
        Place = 2,
        Instance = 3
    }

    public readonly struct ActivityTargetReference
    {
        public ActivityTargetKind Kind { get; }
        public string Id { get; }
        public bool IsValid => Kind != ActivityTargetKind.None
            && !string.IsNullOrWhiteSpace(Id);

        public ActivityTargetReference(ActivityTargetKind kind, string id)
        {
            Kind = kind;
            Id = id?.Trim() ?? string.Empty;
        }

        public static ActivityTargetReference Player(string playerId) =>
            new(ActivityTargetKind.Player, playerId);

        public static ActivityTargetReference Place(string placeId) =>
            new(ActivityTargetKind.Place, placeId);

        public static ActivityTargetReference Instance(string instanceId) =>
            new(ActivityTargetKind.Instance, instanceId);

        public override string ToString() => IsValid
            ? $"{Kind.ToString().ToLowerInvariant()}:{Id}"
            : string.Empty;
    }

    /// <summary>
    /// Metadata common to realtime facts and async persistence. FactRevision
    /// is generated by the Host's authority stream; EventId is the idempotency
    /// key and must remain stable if the same fact is retried.
    /// </summary>
    public readonly struct ActivityFactMetadata
    {
        public string ActorId { get; }
        public string EventId { get; }
        public long OccurredAtUnixMs { get; }
        public uint FactRevision { get; }
        public bool IsValid => !string.IsNullOrWhiteSpace(ActorId)
            && !string.IsNullOrWhiteSpace(EventId)
            && OccurredAtUnixMs > 0
            && FactRevision > 0;

        public ActivityFactMetadata(
            string actorId,
            string eventId,
            long occurredAtUnixMs,
            uint factRevision)
        {
            ActorId = actorId?.Trim() ?? string.Empty;
            EventId = eventId?.Trim() ?? string.Empty;
            OccurredAtUnixMs = occurredAtUnixMs;
            FactRevision = factRevision;
        }

        public static ActivityFactMetadata Create(
            string actorId,
            uint factRevision,
            string eventId = null,
            long occurredAtUnixMs = 0)
        {
            var normalizedActor = actorId?.Trim() ?? string.Empty;
            var normalizedEvent = string.IsNullOrWhiteSpace(eventId)
                ? $"{normalizedActor}:activity:{factRevision}"
                : eventId.Trim();
            var timestamp = occurredAtUnixMs > 0
                ? occurredAtUnixMs
                : DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            return new ActivityFactMetadata(
                normalizedActor,
                normalizedEvent,
                timestamp,
                factRevision);
        }
    }
}
